# This file is named "travis.sample.yml".
# Rename it ".travis.yml".
# http://docs.travis-ci.com/user/build-configuration/

language: cpp

compiler: gcc

before_install:
    - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
    - sudo apt-get update

install:
    - sudo apt-get install clang-3.4
    - sudo apt-get install g++-4.8
    - sudo apt-get install libboost-all-dev
    - sudo apt-get install doxygen
    - sudo apt-get install libgtest-dev
    - cd /usr/src/gtest
    - sudo cmake .
    - sudo make
    - sudo mv libg* /usr/local/lib/
    - cd -
    - sudo apt-get install valgrind

before_script:
    - uname -a
    - set
    - clang++ -v 2>&1 | grep version
    - g++     -v 2>&1 | grep version
    - g++-4.8 -v 2>&1 | grep version
    - head -1 /usr/src/gtest/CHANGES
    - gcov     -version | grep version
    - gcov-4.8 -version | grep version
    - -valgrind --version
    - grep "#define BOOST_VERSION " /usr/include/boost/version.hpp
    - doxygen -v

script:
    - make collatz-tests
    - make html
    - make Collatz.log
    - make test
    - make clean
    - make test CXX=clang++
    - make check
